# Apache SSL Configuration
<VirtualHost *:80>
    ServerName 10.20.20.75
    Redirect permanent / https://10.20.20.75/
</VirtualHost>

<VirtualHost *:443>
    DocumentRoot /var/www/html
    SSLEngine On
    SSLCertificateFile /etc/ssl/certs/MyCertificate.crt
    SSLCertificateKeyFile /etc/ssl/private/MyKey.key
    
    <Directory /var/www/html>
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>
