-- MySQL 8.0 compatible syntax
CREATE USER IF NOT EXISTS 'testuser'@'%' IDENTIFIED BY 'bar';
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,CREATE TEMPORARY TABLES,DROP,INDEX,ALTER ON users.* TO 'testuser'@'%';
FLUSH PRIVILEGES;
